# Butterfly 主题配置

# 头像
avatar:
  img: /img/avatar.png
  effect: true

# 顶部导航栏
nav:
  logo:
  display_title: true
  fixed: false

# 首页
index_img:

# 默认文章封面
default_top_img:

# 文章页
post_meta:
  date_type: created
  date_format: YYYY-MM-DD
  categories: true
  tags: true

# GitHub
social:
  fab fa-github: https://github.com/miraclezznx

# 作者卡片
aside:
  card_author:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/miraclezznx